function t229_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t229__list_item a[href=\''+url+'\'], '+'.t229__list_item a[href=\''+url+'/\'], '+'.t229__list_item a[href=\''+pathname+'\'], '+'.t229__list_item a[href=\'/'+pathname+'\'], '+'.t229__list_item a[href=\''+pathname+'/\'], '+'.t229__list_item a[href=\'/'+pathname+'/\']');Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t229_checkAnchorLinks(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<980)return;var navLinks=rec.querySelectorAll('.t229__list_item a[href*=\'#\']');navLinks=Array.prototype.filter.call(navLinks,function(navLink){return!navLink.classList.contains('tooltipstered')});if(navLinks.length){t229_catchScroll(navLinks)}}
function t229_catchScroll(navLinks){navLinks=Array.prototype.slice.call(navLinks);var clickedSectionID=null;var sections=[];var sectionToNavigationLinkID={};var interval=100;var lastCall;var timeoutID;if(Array.isArray(navLinks)){navLinks=navLinks.reverse()}
Array.prototype.forEach.call(navLinks,function(link){var currentSection=t229_getSectionByHref(link);if(currentSection&&currentSection.id){sections.push(currentSection);sectionToNavigationLinkID[currentSection.id]=link}});t229_updateSectionsOffsets(sections);sections.sort(function(a,b){var firstTopOffset=parseInt(a.getAttribute('data-offset-top'),10)||0;var secondTopOffset=parseInt(b.getAttribute('data-offset-top'),10)||0;return secondTopOffset-firstTopOffset});window.addEventListener('resize',t_throttle(function(){t229_updateSectionsOffsets(sections)},200));if(typeof jQuery!=='undefined'){$('.t229').bind('displayChanged',function(){t229_updateSectionsOffsets(sections)})}else{var menuEls=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuEls,function(menu){menu.addEventListener('displayChanged',function(){t229_updateSectionsOffsets(sections)})})}
setInterval(function(){t229_updateSectionsOffsets(sections)},5000);t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID);Array.prototype.forEach.call(navLinks,function(navLink,i){navLink.addEventListener('click',function(){var clickedSection=t229_getSectionByHref(navLink);if(!navLink.classList.contains('tooltipstered')&&clickedSection&&clickedSection.id){navLinks.forEach(function(link,index){if(index===i){link.classList.add('t-active')}else{link.classList.remove('t-active')}});clickedSectionID=clickedSection.id}})});window.addEventListener('scroll',function(){var dateNow=new Date().getTime();if(lastCall&&dateNow<lastCall+interval){clearTimeout(timeoutID);timeoutID=setTimeout(function(){lastCall=dateNow;clickedSectionID=t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)},interval-(dateNow-lastCall))}else{lastCall=dateNow;clickedSectionID=t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID)}})}
function t229_updateSectionsOffsets(sections){sections.forEach(function(section){var sectionTopPos=section.getBoundingClientRect().top+window.pageYOffset;section.setAttribute('data-offset-top',sectionTopPos)})}
function t229_getSectionByHref(curlink){if(!curlink)return;var href=curlink.getAttribute('href');var curLinkValue=href?href.replace(/\s+/g,''):'';if(curLinkValue.indexOf('/')===0)curLinkValue=curLinkValue.slice(1);if(href&&curlink.matches('[href*="#rec"]')){curLinkValue=curLinkValue.replace(/.*#/,'');return document.getElementById(curLinkValue)}else{var selector=href?href.trim():'';var slashIndex=selector.indexOf('#')!==-1?selector.indexOf('#'):!1;if(typeof slashIndex==='number'){selector=selector.slice(slashIndex+1)}else{slashIndex=selector.indexOf('/')!==-1?selector.indexOf('/'):!1;if(typeof slashIndex==='number')selector=selector.slice(slashIndex+1)}
var fullSelector='.r[data-record-type="215"] a[name="'+selector+'"]';return document.querySelector(fullSelector)?document.querySelector(fullSelector).closest('.r'):null}}
function t229_highlightNavLinks(navLinks,sections,sectionToNavigationLinkID,clickedSectionID){var scrollPosition=window.pageYOffset;var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var returnValue=clickedSectionID;var lastSection=sections.length?sections[sections.length-1]:null;var lastSectionTopPos=lastSection?lastSection.getAttribute('data-offset-top'):'0';lastSectionTopPos=parseInt(lastSectionTopPos,10)||0;if(sections.length&&clickedSectionID===null&&lastSectionTopPos>(scrollPosition+300)){navLinks.forEach(function(link){link.classList.remove('t-active')});return null}
for(var i=0;i<sections.length;i++){var sectionTopPos=sections[i].getAttribute('data-offset-top');var navLink=sections[i].id?sectionToNavigationLinkID[sections[i].id]:null;if(scrollPosition+300>=sectionTopPos||i===0&&scrollPosition>=scrollHeight-window.innerHeight){if(clickedSectionID===null&&navLink&&!navLink.classList.contains('t-active')){navLinks.forEach(function(link){link.classList.remove('t-active')});if(navLink)navLink.classList.add('t-active');returnValue=null}else if(clickedSectionID!==null&&sections[i].id&&clickedSectionID===sections[i].id){returnValue=null}
break}}
return returnValue}
function t229_setBg(recid){var menuBlocks=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){if(window.innerWidth>980){if(menu.getAttribute('data-bgcolor-setbyscript')==='yes'){menu.style.backgroundColor=menu.getAttribute('data-bgcolor-rgba')}}else{menu.style.backgroundColor=menu.getAttribute('data-bgcolor-hex');menu.setAttribute('data-bgcolor-setbyscript','yes');if(menu.style.transform)menu.style.transform='';if(menu.style.opacity)menu.style.opacity=''}})}
function t229_appearMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec||window.innerWidth<=980)return;var menuBlocks=rec.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){var appearOffset=menu.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')!==-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);var menuHeight=menu.clientHeight;if(typeof appearOffset==='number'&&window.pageYOffset>=appearOffset){if(menu.style.transform==='translateY(-'+menuHeight+'px)'){t229_slideUpElement(menu,menuHeight,'toBottom')}}else if(menu.style.transform==='translateY(0px)'){t229_slideUpElement(menu,menuHeight,'toTop')}else{menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0'}}})}
function t229_slideUpElement(menu,menuHeight,position){var diff=position==='toTop'?0:menuHeight;var diffOpacity=position==='toTop'?1:0;var timerID=setInterval(function(){menu.style.transform='translateY(-'+diff+'px)';menu.style.opacity=diffOpacity.toString();diffOpacity=position==='toTop'?diffOpacity-0.1:diffOpacity+0.1;diff=position==='toTop'?diff+(menuHeight/20):diff-(menuHeight/20);if(position==='toTop'&&diff>=menuHeight){menu.style.transform='translateY(-'+menuHeight+'px)';menu.style.opacity='0';clearInterval(timerID)}
if(position==='toBottom'&&diff<=0){menu.style.transform='translateY(0px)';menu.style.opacity='1';clearInterval(timerID)}},10)}
function t229_changeBgOpacityMenu(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t229');Array.prototype.forEach.call(menuBlocks,function(menu){var bgColor=menu.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=menu.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=menu.getAttribute('data-bgopacity');var bgOpacityTwo=menu.getAttribute('data-bgopacity-two');var menuShadow=menu.getAttribute('data-menushadow')||'0';var menuShadowValue=menuShadow==='100'?menuShadow:'0.'+menuShadow;menu.style.backgroundColor=window.pageYOffset>20?bgColorAfterScroll:bgColor;if(window.pageYOffset>20&&bgOpacityTwo==='0'||window.pageYOffset<=20&&bgOpacity==='0.0'||menuShadow===' '){menu.style.boxShadow='none'}else{menu.style.boxShadow='0px 1px 3px rgba(0,0,0,'+menuShadowValue+')'}})}
function t270_scroll(hash,offset,speed){if(!speed)speed=400;if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var target;if(!hash)return;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return!0}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;target=parseInt(target.getBoundingClientRect().top+window.pageYOffset-offset,10);t270_scrollToEl(target);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_scrollToEl(target,duration){if(!duration){duration=400}
if(target===window.pageYOffset){return!1}
var difference=window.pageYOffset;var cashedDiff=window.pageYOffset;var step=(Math.abs(window.pageYOffset-target)*10)/duration;var scrollInterval=setInterval(function(){if(cashedDiff>target){difference-=step}else{difference+=step}
window.scrollTo(0,difference);document.body.setAttribute('data-scrollable','true');if(cashedDiff>target&&window.pageYOffset<=target){document.body.removeAttribute('data-scrollable');clearInterval(scrollInterval)}else if(cashedDiff<=target&&window.pageYOffset>=target){document.body.removeAttribute('data-scrollable');window.scrollTo(0,target);clearInterval(scrollInterval)}},10);var scrollTimeout=setTimeout(function(){clearInterval(scrollInterval);document.body.removeAttribute('data-scrollable');clearTimeout(scrollTimeout)},duration*2)}
function t602_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var indicator=rec.querySelector('.t602__indicator');if(!indicator)return;window.addEventListener('scroll',t_throttle(function(){var documentHeight=document.body.clientHeight;var windowScrollTop=document.documentElement.scrollTop;var windowHeight=window.innerHeight;var scrollPercent=(windowScrollTop/(documentHeight-windowHeight))*100;indicator.style.width=scrollPercent+'%'},100))}
function t706_onSuccessCallback(){var products=document.querySelector('.t706__cartwin-products');var cartBottom=document.querySelector('.t706__cartwin-bottom');var cartForm=document.querySelector('.t706 .t-form__inputsbox');if(products)t706_slideUp(products,10);if(cartBottom)t706_slideUp(cartBottom,10);if(cartForm)t706_slideUp(cartForm,700);try{tcart__unlockScroll()}catch(error){}}
function t706_slideUp(target,duration){if(!target)return;if(!duration&&duration!==0)duration=500;target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.boxSizing='border-box';target.style.height=target.offsetHeight+'px';target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';setTimeout(function(){target.style.display='none';target.style.height='';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}